[workspace]
members = ["modulus-bin"]

[package]
name = "modulus"
version = "0.0.0"
edition = "2021"
description = "A small, modular, embeddable programing language"
authors = ["Jacob Stannix <jakestannix@gmail.com>"]
